modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/Lance5057/Butchercraft/issues"

[[mods]]
	modId = "butchercraft"
	version="${file.jarVersion}"
	displayName = "Butchercraft"
	displayURL = "https://github.com/Lance5057/Butchercraft"
	credits = "Alan199921, DivineAspect, Skysom, FreneticScribbler, Lanse505, Belathus, RoyalJelly"
	authors = "Lance5057"